spring:
  application:
    name: backend
  jpa:
    open-in-view: false

storage:
  aws:
    bucket-name: archive-digitalisation-v1
  local:
    base-dir-path: /app/files

syncfusion:
  license-key: adfs

auth:
  base-url: http://localhost:4000
  path: /api/v1/token/verify
  connect-timeout-ms: 1000
  read-timeout-ms: 1500
  bypass-token: ${AUTH_BYPASS_TOKEN:agsrgbbgadfaa}

ocr:
  base-url: http://localhost:8000
  path: /ocr/process
  information-path: /ocr/available_models

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.FilterChainProxy: TRACE
