spring:
  datasource:
    url: jdbc:postgresql://db_backend:5432/backend
    username: postgres_backend
    password: password
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update